apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: Helmraiser
    app.tanka.grafana.com: kubearmor
  name: kubearmor-controller-webhook-service
  namespace: kubearmor
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    kubearmor-app: kubearmor-controller
