apiVersion: instagramclone.io/v1alpha1
kind: Application
metadata:
  name: followships-microservice
  namespace: microservices

spec:
  image: ghcr.io/archisman-mridha/instagram-clone-followships-microservice:07db74b3dd4888026a2e852c6fca860157aa910a
  replicas:
    min: 1
    max: 3
  resources:
    cpu: 100m
    memory: 100Mi
  secretName: followships-microservice
  ports:
    - name: grpc
      containerPort: 4000
      protocol: tcp
    - name: metrics
      containerPort: 5000
      protocol: http
