apiVersion: instagramclone.io/v1alpha1
kind: Application
metadata:
  name: frontend-microservice
  namespace: microservices
  labels:
    app: frontend-microservice
    app.kubernetes.io/instance: frontend-microservice

spec:
  image: ghcr.io/archisman-mridha/instagram-clone-frontend-microservice:a856ea0a513f9ad8f01978ef5eb206c61447a34a
  replicas:
    min: 1
    max: 3
  resources:
    cpu: 200m
    memory: 200Mi
  secretName: frontend-microservice
  ports:
    - name: web
      containerPort: 3000
