---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: main-es-elastic-user
  namespace: elasticsearch
spec:
  encryptedData:
    elastic: AgCQ1yRg3vhnfw3KhBYhL6ObBRqzGafUqgjH89CKgHZoR/rBU3G8gFYXz21kDzmbUUVrugz/k7NNC1hFz0WEEiQpKM5p2ZA/iwlvfXHD/vV0kxm/77jaqQxOjRKOacrTbFw1CL07SnF6ihVILI0qU69JZlOUdR4bR1MiPUpQwGjlMjzSC/GjYm3ivTM5BnIVZepV7XlF50JtmolM36wsOwaf9/pz6jilHeiA4mWRG00+a1axXQjic/Ja3q/emZ7k1SfWBPcGv8aufACx+LLr/pMfzKgtcw+dsEeg6z2FAINpa9CP3kHrJnrRpEKMgF7LxhF7DRq0X4Ak1yQ8ehdXPRIaqeQ7DoyqDDGmGT1ub8jOc35zwgO6S02ivdzYphdiwlIpl81qfMjM9A++giyTSEDctzRd2Up5pCltRLRm556/l9CKJrUUsFfY7u2ElirTRJWVMODdNeOhr0gqr4b3Y11g3G5s8E+jTYPT5uvZfHPbFxHj4Or7JP7KGJu2p7ukq/Y4o4WONByREjY5AbUrumWm5xMVC04M47KWnJouHfs5lNRXVdu5uuBE9lpG7Kl1/zbIZmqh+Cd43CagOYeZE/OMCq4n6xMiRs3YFERPha87W6a2uj6vUntMWz/7UA3Y3MpMcsd0avMaaoN2PM5qUvf0NOztwBYAUeLfbuvba7RwKLFXsw8WTuxt/mJqTMv8cx1tQUbH
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: main-es-elastic-user
      namespace: elasticsearch
    type: Opaque
