apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/version: 0.21.0
    app.tanka.grafana.com: external-dns
    helm.sh/chart: external-dns-1.21.1
  name: external-dns
  namespace: external-dns
spec:
  ports:
    - name: http
      port: 7979
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/name: external-dns
  type: ClusterIP
