apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/Archisman-Mridha/instagram-clone
    targetRevision: ${WORKSPACE}
    path: kubernetes/workspaces/${WORKSPACE}

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true