---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: cert-manager
spec:
  encryptedData:
    api-key: AgA5uF1ELVgM239WFuRXiWhxfe2z5dj/Pzo4Gtpzi2FcW2FLuUOvS7aEvQpRHBvsoxxLsgOcsiOvDx0ZctU8gC+3af4LYXjpkVVsjzQKFL9nV2HXwl9Pvp7/3qhQ1nhd3BPhQFvyJYjVbn8xRIqtziEW+126QsdBNnxdWQKbvV78N4p6UCg4AZOa2+OiBVCn8MvvMeg5t03K6lECMJ9KEy5fkxQ18rinU7WR71klnoQzOWwM6vfa7Hvxw34u6yB/GpfcanVwDZA4SxUE39gm9VywZFTCVt6PJKJE7c5U4Ks/d9MWGnz2sSCi+29EawcbUL+FKmPcKS/vDi7Y4TFQSNheW2cSMR439czEqnMrTNMppiqzM9wIULRDaPjy4wTuq9XTBBL/d6BOn+/mTFQEwnSI5jkA6MBAvh3aYPFIfQBhGgp+rwcdzhs7DhVzka7j/lkbiBxVfofPaFWN3rCNO0ygh/JvXOvxeNZgTc+uMmn9tUhl3bfv4V2QnHNGawnkwM1Tim1MKLuxq80gD4GKmFLjfRNF62Qs/rgf+hdbY1yJyh/uSCTseJ8xETf8XLDeV5wNz4VvMwheBoCZY3uf5H2xE5/sggglTIB5mTAEUDybosd0OYk/jrMuvkJGew/E5izXInwcILujYaGkDUojpBgSpPkUloIYTAlIXdgr0Mxy7EItYzwp36pezCQ5K57wTQOLuyfjrl+vW4QXkLPbnWlKLFUJPOEA2FO4WX/ox8hZb+B6id2q
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: cert-manager
