resources:
  - ./namespace.yaml

  ## Install CRDs
  - https://github.com/cert-manager/cert-manager/releases/download/v1.13.1/cert-manager.crds.yaml

  - ./cluster-issuer.yaml
  - ./cloudflare-api-key.sealed-secret.yaml

helmCharts:
  ## CertManager adds certificates and certificate issuers as resource types in Kubernetes clusters,
  ## and simplifies the process of obtaining, renewing and using those certificates. It can issue
  ## certificates from a variety of supported sources, including Let's Encrypt, HashiCorp Vault etc.
  ## It will ensure certificates are valid and up to date, and attempt to renew certificates at a
  ## configured time before expiry.
  - repo: https://charts.jetstack.io/
    name: cert-manager
    version: 1.13.1
    namespace: cert-manager
    releaseName: cert-manager