apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: staging.openmedia
spec:
  # Become tags in AWS on the instances.
  cloudLabels:
    project: openmedia
    environment: staging

  cloudProvider:
    aws:
      ebsCSIDriver:
        enabled: false
      nodeTerminationHandler:
        enabled: false

  networkCIDR: 10.0.0.0/16
  subnets:
    - name: public-a
      zone: us-east-2a
      type: Utility
    - name: public-b
      zone: us-east-2b
      type: Utility
    - name: public-c
      zone: us-east-2c
      type: Utility

    - name: private-a
      zone: us-east-2a
      type: Private
    - name: private-b
      zone: us-east-2b
      type: Private
    - name: private-c
      zone: us-east-2c
      type: Private
  networking:
    podCIDR: 10.244.0.0/16
  nonMasqueradeCIDR: 10.244.0.0/16

  kubernetesApiAccess:
    - 152.115.110.158/32

  sshKeyName: clusters-admin
  sshAccess:
    - 152.115.110.158/32

  topology:
    dns:
      type: None

  api:
    loadBalancer:
      class: Network
      type: Public

  kubernetesVersion: v1.33.0

  etcdClusters:
    - name: main
      etcdMembers:
        - name: a
          instanceGroup: master-a
          # By default, the Volumes created for the etcd clusters are gp3 and 20GB each.
          volumeSize: 10
          encryptedVolume: true
          # - name: b
          #   instanceGroup: master-b
          #   volumeSize: 10
          #   encryptedVolume: true
          # - name: c
          #   instanceGroup: master-c
          #   volumeSize: 10
          #   encryptedVolume: true
      manager:
        env:
          - name: ETCD_METRICS
            value: extensive
          - name: ETCD_LISTEN_METRICS_URLS
            value: "http://0.0.0.0:8081"

  # In a default Kubernetes setup, every resource type shares a single etcd cluster. Pods,
  # deployments, configmaps, secrets, events, leases, and custom resources all write to the same
  # Raft log, the same bbolt file, the same leader.
  #
  # In a busy cluster, the event stream can generate hundreds of writes per second, and those
  # writes compete with deployment rollouts and config map updates for the same Raft leader.
  # Now, events are written to a separate Raft log, a separate bbolt file, and a separate leader
  # and Event churn no longer competes with deployment rollouts for resources.
  #
  # You can shard any built-in resource this way.
  #
  # REFER: https://learnkube.com/etcd-breaks-at-scale.

  # - name: events
  #   etcdMembers:
  #     - name: a
  #       instanceGroup: master-a
  #       volumeSize: 10
  #       encryptedVolume: true
  #     - name: b
  #       instanceGroup: master-b
  #       volumeSize: 10
  #       encryptedVolume: true
  #     - name: c
  #       instanceGroup: master-c
  #       volumeSize: 10
  #       encryptedVolume: true
  #   manager:
  #     env:
  #       - name: ETCD_METRICS
  #         value: extensive
  #       - name: ETCD_LISTEN_METRICS_URLS
  #         value: "http://0.0.0.0:8082"

  fileAssets:
    - name: kube-system-cgroup-manager
      path: /etc/systemd/system/kube-system-cgroup-manager.service.d/10-kube-system-cgroup.conf
      roles:
        - ControlPlane
        - Node
      content: |
        [Service]
        Slice=kube-system.slice

    - name: audit-policy
      path: /etc/kubernetes/audit/policy-config.yaml
      roles:
        - ControlPlane
      content: |
        apiVersion: audit.k8s.io/v1
        kind: Policy
        rules:
          - level: Metadata

  kubeAPIServer:
    # Kubernetes auditing provides a security-relevant, chronological set of records documenting
    # the sequence of actions in a cluster. The cluster audits the activities generated by users,
    # by applications that use the Kubernetes API, and by the control plane itself.
    auditPolicyFile: /etc/kubernetes/audit/policy-config.yaml

    # Audit backends persist audit events to an external storage.
    # We're going to use the log backend: which writes events into the filesystem.

    # Specifies the log file path that log backend uses to write audit events.
    auditLogPath: /var/log/kube-apiserver-audit.log

    # Defines the maximum number of days to retain old audit log files.
    auditLogMaxAge: 30

    # Defines the maximum number of audit log files to retain.
    auditLogMaxBackups: 10

    # Defines the maximum size in megabytes of the audit log file before it gets rotated.
    auditLogMaxSize: 100

  kubelet:
    # By default, requests to the kubelet's HTTPS endpoint that are not rejected by other
    # configured authentication methods are treated as anonymous requests, and given a username of
    # system:anonymous and a group of system:unauthenticated.
    # Disable anonymous access and send 401 Unauthorized responses to unauthenticated requests.
    anonymusAuth: false

    # By default, the kubelet uses CFS quota to enforce pod CPU limits.
    # We'll disable that, so pod CPU limits won't take effect.
    cpuCFSQuota: false

    # Kubernetes nodes can be scheduled to Capacity. Pods can consume all the available capacity
    # on a node by default. This is an issue because nodes typically run quite a few system
    # daemons that power the OS and Kubernetes itself. Unless resources are set aside for these
    # system daemons, pods and system daemons compete for resources and lead to resource
    # starvation issues on the node.
    # The kubelet exposes a feature named 'Node Allocatable' that helps to reserve compute
    # resources for system daemons. Kubernetes recommends cluster administrators to configure
    # 'Node Allocatable' based on their workload density on each node.

    # systemReserved is meant to capture resource reservation for OS system daemons like sshd,
    # udev, etc. systemReserved should reserve memory for the kernel too since kernel memory is
    # not accounted to pods in Kubernetes at this time. Reserving resources for user login
    # sessions is also recommended (user.slice in systemd world).
    systemReserved:
      cpu: 500m
      memory: 1Gi
      ephemeral-storage: 1Gi
    systemReservedCgroup: /system.slice

    # kubeReserved is meant to capture resource reservation for kubernetes system daemons like the
    # kubelet, container runtime, etc. It is not meant to reserve resources for system daemons
    # that are run as pods.
    kubeReserved:
      cpu: 250m
      memory: 2Gi
      ephemeral-storage: 1Gi
    kubeReservedCgroup: /kube-system.slice

    # kubelet enforces 'Allocatable' across pods by default. Enforcement is performed by evicting
    # pods whenever the overall usage across all pods exceeds 'Allocatable'.
    # Optionally, kubelet can be made to enforce kubeReserved and systemReserved by specifying
    # kube-reserved & system-reserved values in the same setting. Additionally, only compressible
    # resources may be enforced by specifying kube-reserved-compressible and
    # system-reserved-compressible. Note that to enforce kubeReserved or systemReserved,
    # kubeReservedCgroup or systemReservedCgroup needs to be specified respectively.
    enforceNodeAllocatable: pods,system-reserved,kube-reserved

  # Applications in a Pod’s containers can use an AWS SDK or the AWS CLI to make API requests to
  # AWS services using AWS Identity and Access Management (IAM) permissions. Applications must sign
  # their AWS API requests with AWS credentials. IAM roles for service accounts (IRSA) provide the
  # ability to manage credentials for your applications, similar to the way that Amazon EC2
  # instance profiles provide credentials to Amazon EC2 instances. Instead of creating and
  # distributing your AWS credentials to the containers or using the Amazon EC2 instance’s role,
  # you associate an IAM role with a Kubernetes service account and configure your Pods to use the
  # service account.
  #
  # IAM roles for service accounts provide the following benefits:
  #
  #   (1) Least privilege – You can scope IAM permissions to a service account, and only Pods that
  #       use that service account have access to those permissions. This feature also eliminates
  #       the need for third-party solutions such as kiam or kube2iam.
  #
  #   (2) Credential isolation – When access to the Amazon EC2 Instance Metadata Service (IMDS) is
  #       restricted, a Pod’s containers can only retrieve credentials for the IAM role that’s
  #       associated with the service account that the container uses. A container never has access
  #       to credentials that are used by other containers in other Pods. If IMDS is not restricted,
  #       the Pod’s containers also have access to the Amazon EKS node IAM role and the containers
  #       may be able to gain access to credentials of IAM roles of other Pods on the same node.
  #
  #   (3) Auditability – Access and event logging is available through AWS CloudTrail to help
  #       ensure retrospective auditing.
  #
  # kOps can publish the Kubernetes service account token issuer and configure AWS to trust it to
  # authenticate Kubernetes service accounts.
  serviceAccountIssuerDiscovery:
    discoveryStore: s3://irsa-discovery-store-staging-openmedia
    enableAWSOIDCProvider: true

  cloudControllerManager:
    # Should CIDRs allocated by allocate-node-cidrs (enabled by default) be configured on the cloud
    # provider.
    configureCloudRoutes: true

  # By default kops will create StorageClass resources with some opinionated settings specific to
  # cloud provider on which the cluster is installed. One of those storage classes will be defined
  # as default applying the annotation storageclass.kubernetes.io/is-default-class: "true".
