[package]
name = "instagram-clone"
version = "0.1.0"
edition = "2021"

[[bin]]
name= "users-microservice"
path= "backend/microservices/users/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
tonic-build = "0.10.2"
