[package]
name = "instagram-clone"
version = "0.1.0"
edition = "2021"

[[bin]]
name= "users-microservice"
path= "backend/microservices/users/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.78"
dotenv = "0.15.0"
lazy_static = "1.4.0"
prost = "0.12.3"
tokio = { version = "1.35.1", features = ["rt-multi-thread", "macros", "signal"] }
tokio-util = "0.7.10"
tonic = { version = "0.10.2", features = ["gzip"] }
tonic-reflection = "0.10.2"

[build-dependencies]
tonic-build = "0.10.2"
