version: '3'

services:

  postgres:
    container_name: postgres
    image: postgres:alpine
    environment:
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=instagram_clone
    ports:
      - 5432:5432
    ## 'wal_level = logical' is the highest level of WAL logging.
    command: ["postgres", "-c", "wal_level=logical", "-c", "max_replication_slots=4", "-c", "max_wal_senders=4"]
    healthcheck:
      test: ["CMD", "psql", "-U", "default", "-d", "instagram_clone", "-c", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-migrate:
    container_name: postgres-migrate
    image: migrate/migrate:latest
    volumes:
      - ./backend/sql/schema.sql:/migrations/000001_init.up.sql:ro
    command:  ["-path", "/migrations", "-database",  "postgres://default:pass@postgres:5432/instagram_clone?sslmode=disable", "up"]
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure