version: v2beta1
name: instagram-clone

pipelines:
  dev-authentication-microservice:
    run: |-
      create_deployments authentication-db authentication-microservice
      start_dev authentication-microservice

images:
  authentication-microservice:
    image: archismanmridha/instagram-clone-authentication-microservice
    dockerfile: ./backend/services/authentication/Dockerfile
    context: .

deployments:

  authentication-db:
    kubectl:
      kustomize: true
      manifests:
        - ./kubernetes/base/microservices/authentication/db
  authentication-microservice:
    kubectl:
      manifests:
        - ./kubernetes/base/microservices/authentication/deployment.yaml
        - ./kubernetes/base/microservices/authentication/sealed-secret.yaml

dev:
  authentication-microservice:
    namespace: default
    workingDir: /app
    imageSelector: archismanmridha/instagram-clone-authentication-microservice
    devImage: ghcr.io/loft-sh/devspace-containers/go:1.20-alpine
    sync:
      - path: ./backend/services/authentication/:/app/backend/services/authentication
      - path: ./backend/proto/generated/:/app/backend/proto/generated
      - path: ./backend/shared/:/app/backend/shared
    terminal:
      command: /app/backend/services/authentication/devspace_start.sh
    ssh:
      enabled: true
    proxyCommands:
      - command: kubectl
      - gitCredentials: true
    ports:
      - port: "4000"
    resources:
      limits:
        memory: 1Gi
        cpu: 2000m