CREATE TABLE users (
  id SERIAL PRIMARY KEY,

  is_verified BOOLEAN DEFAULT FALSE,

  name VARCHAR(50) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  username VARCHAR(50),
  password VARCHAR(50)
);