apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  labels:
    app.tanka.grafana.com: openmedia
    strimzi.io/cluster: openmedia
  name: openmedia-brokers
  namespace: openmedia
spec:
  replicas: 3
  roles:
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        kraftMetadata: shared
        size: 5Gi
        type: persistent-claim
