apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/created-by: dragonfly-operator
    app.kubernetes.io/instance: dragonfly
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: dragonfly-operator
    app.kubernetes.io/part-of: dragonfly-operator
    app.kubernetes.io/version: v1.5.0
    app.tanka.grafana.com: dragonfly
    control-plane: controller-manager
    helm.sh/chart: dragonfly-operator-v1.5.0
  name: dragonfly-dragonfly-operator
  namespace: dragonfly
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: dragonfly
      app.kubernetes.io/name: dragonfly-operator
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/created-by: dragonfly-operator
        app.kubernetes.io/instance: dragonfly
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: dragonfly-operator
        app.kubernetes.io/part-of: dragonfly-operator
        app.kubernetes.io/version: v1.5.0
        control-plane: controller-manager
        helm.sh/chart: dragonfly-operator-v1.5.0
    spec:
      containers:
        - args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            - --v=0
          image: quay.io/brancz/kube-rbac-proxy:v0.20.2
          imagePullPolicy: IfNotPresent
          name: kube-rbac-proxy
          ports:
            - containerPort: 8443
              name: https
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
        - args:
            - --leader-elect
            - --metrics-bind-address=127.0.0.1:8080
          command:
            - /manager
          image: docker.dragonflydb.io/dragonflydb/operator:v1.5.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          name: manager
          ports:
            - containerPort: 8080
              name: metrics
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      securityContext:
        runAsNonRoot: true
      serviceAccountName: dragonfly-operator-controller-manager
      terminationGracePeriodSeconds: 10
