apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasSchema
metadata:
  name: authentication-db-schema
  namespace: default
  labels:
    app.kubernetes.io/part-of: authentication-microservice

spec:
  urlFrom:
    secretKeyRef:
      key: url
      name: authentication-db-url
  schema:
    sql: |
      CREATE TABLE users (
        id SERIAL PRIMARY KEY,

        email VARCHAR(255) NOT NULL UNIQUE,
        username VARCHAR(50) NOT NULL UNIQUE,

        password VARCHAR(50) NOT NULL,

        is_verified BOOLEAN DEFAULT FALSE
      );

      CREATE TABLE outbox (
        id SERIAL PRIMARY KEY,

        message BYTEA NOT NULL,

        locked BOOLEAN DEFAULT FALSE,
        locked_on TIMESTAMP DEFAULT NULL,

        published BOOLEAN DEFAULT FALSE
      );