apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: sealed-secrets-tls-key
  namespace: kube-system
  labels:
    sealedsecrets.bitnami.com/sealed-secrets-key: active

data:
  tls.crt: ${TLS_CRT}
  tls.key: ${TLS_KEY}