apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgres-kafka-connect-cluster
  namespace: strimzi

rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["postgres-credentials"]
    verbs: ["get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgres-kafka-connect-cluster
  namespace: strimzi

roleRef:
  kind: Role
  name: postgres-kafka-connect-cluster
  apiGroup: rbac.authorization.k8s.io

subjects:
  # The service account will be created by Strimzi once we deploy the Kafka Connect cluster.
  - kind: ServiceAccount
    name: postgres-connect
    namespace: strimzi