apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: dex-server
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: argocd-dex-server
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v3.4.3
    app.tanka.grafana.com: argo-cd
    helm.sh/chart: argo-cd-9.5.19
  name: argo-cd-argocd-dex-server
  namespace: argo-cd
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - list
      - watch
