apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: Helmraiser
    app.tanka.grafana.com: openkruise
  name: kruise-daemon-secret-rolebinding
  namespace: kruise-daemon-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kruise-daemon-secret-role
subjects:
  - kind: ServiceAccount
    name: kruise-daemon
    namespace: kruise-system
