apiVersion: v1
data: {}
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: cloudnative-pg
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: cloudnative-pg
    app.kubernetes.io/version: 1.29.1
    app.tanka.grafana.com: cloudnative-pg
    helm.sh/chart: cloudnative-pg-0.28.2
  name: cnpg-controller-manager-config
  namespace: cloudnative-pg
