apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "20257"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
  labels:
    app: node-problem-detector
    app.kubernetes.io/instance: node-problem-detector
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: node-problem-detector
    app.tanka.grafana.com: node-problem-detector
    helm.sh/chart: node-problem-detector-2.4.1
  name: node-problem-detector
  namespace: node-problem-detector
spec:
  clusterIP: None
  ports:
    - name: exporter
      port: 20257
      protocol: TCP
  selector:
    app: node-problem-detector
  type: ClusterIP
