apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: opencost
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: opencost
    app.kubernetes.io/part-of: opencost
    app.kubernetes.io/version: 1.120.3
    app.tanka.grafana.com: opencost
    helm.sh/chart: opencost-2.5.22
  name: opencost-pvc
  namespace: opencost
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
