apiVersion: v1
kind: Service
metadata:
  labels:
    app: operator
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/part-of: kubescape
    app.kubernetes.io/version: 1.40.2
    app.tanka.grafana.com: kubescape
    helm.sh/chart: kubescape-operator-1.40.2
    kubescape.io/ignore: "true"
    tier: ks-control-plane
  name: kubescape-admission-webhook
  namespace: kubescape
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/name: kubescape-operator
  type: ClusterIP
