apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-agent
    app.kubernetes.io/component: node-agent
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/part-of: kubescape
    app.kubernetes.io/version: 1.40.2
    app.tanka.grafana.com: kubescape
    helm.sh/chart: kubescape-operator-1.40.2
    kubescape.io/ignore: "true"
    tier: ks-control-plane
  name: node-agent
  namespace: kubescape
spec:
  ports:
    - name: prometheus
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/component: node-agent
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/name: kubescape-operator
