apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: storage
    app.kubernetes.io/component: storage
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/part-of: kubescape
    app.kubernetes.io/version: 1.40.2
    app.tanka.grafana.com: kubescape
    helm.sh/chart: kubescape-operator-1.40.2
    kubescape.io/ignore: "true"
    tier: ks-control-plane
  name: kubescape-storage
  namespace: kubescape
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
