apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-prometheus-stack-operator
    app.kubernetes.io/component: prometheus-operator
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: kube-prometheus-stack-prometheus-operator
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 86.1.0
    app.tanka.grafana.com: kube-prometheus-stack
    chart: kube-prometheus-stack-86.1.0
    heritage: Helm
    release: kube-prometheus-stack
  name: kube-prometheus-stack-operator
  namespace: kube-prometheus-stack
spec:
  ports:
    - name: https
      port: 443
      targetPort: https
  selector:
    app: kube-prometheus-stack-operator
    release: kube-prometheus-stack
  type: ClusterIP
