apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  labels:
    app.tanka.grafana.com: openmedia
  name: openmedia
  namespace: openmedia
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      auto.create.topics.enable: false
      default.replication.factor: 3
      min.insync.replicas: 2
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
    metadataVersion: 4.2-IV1
    version: 4.2.0
