apiVersion: instagramclone.io/v1alpha1
kind: Application
metadata:
  name: gateway-microservice
  namespace: microservices

spec:
  image: ghcr.io/archisman-mridha/instagram-clone-gateway:2420c7e7f17085462ddce5bfe7eeb37f1b308c4a
  replicas:
    min: 1
    max: 3
  resources:
    cpu: 100m
    memory: 100Mi
  secretName: gateway-microservice
  ports:
    - name: grpc
      containerPort: 4000
    - name: metrics
      containerPort: 5000
