apiVersion: v1
data:
  admin-password: UW1qSDVHVXhIMXlnYW5HWDFzeXY5Tk9rTm4yY2ZoY0RVQWc0VGR0bw==
  admin-user: YWRtaW4=
  ldap-toml: ""
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: admin-secret
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 13.0.1-security-01
    app.tanka.grafana.com: kube-prometheus-stack
    helm.sh/chart: grafana-12.4.1
  name: kube-prometheus-stack-grafana
  namespace: kube-prometheus-stack
type: Opaque
