apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-cluster-secret-backend
  namespace: rabbitmq
  labels:
    app.kubernetes.io/part-of: rabbitmq
type: Opaque

stringData:
  default_user.conf: |
    default_user = admin
    default_pass = pass