apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: adam
spec:
  signerName: kubernetes.io/kube-apiserver-client
  groups:
    - database-engineers
  request:
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZEQ0NBVHdDQVFBd0R6RU5NQXNHQTFVRUF3d0VZV1JoYlRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRApnZ0VQQURDQ0FRb0NnZ0VCQU1OSERFME1NNTllM1JaZGp1Y0R5bzRQUW1ubko5Q1lOZFNGWXgxellJR0t6WWhSCnZXcHJDTit4ZUxJNCtnOTJ1ZGZvZS9OWHE2MVM5SjJadHVHOSsxU08wUnlDVzZhYXdwVEJ1MDBpRGRGcEQrQnQKSnpMdzcvZEw4R2JiQ0VOTDJFZytMQXhZa21laVRid00vT2U3VWN2cUdNazgvZVQ1c3ZzYVIzOXBvL1I2aGUzQwp3UzZ5cysvd1VsdXlQZk01NGVRNnB2bnlJdWFoUEhIVDdMS2hjcVMveHFjclJWY0lIWmJ3dVBHbGVyOXI2d3UvCmFRZjhiVVhYVEhzVUhOb3lyZlZWZ3NGN29ZZG9ESEFaS0d3ejJkczFEYk1adnNFMkpybzJIQXE1aWtMK0c0ZXIKNjRKRmE0b3pBdHl4NVErbDBUaW1sbWNQRnh3TnlYQmd6bHVMN1hjQ0F3RUFBYUFBTUEwR0NTcUdTSWIzRFFFQgpDd1VBQTRJQkFRQSsxZnhlQ3h3STMxSzViT3N4UWxIUDFwc00wcHQ3b2d3M3ZTTmhocHkyOHA0UGRkWE9FbHpaCjhUcG5Ddk9hRy93Qy9jNWZCMTduUVFOMmo2bGNrcHJGM0RTODVEZHBoL0tRZFROb3VVU2lzSXBnQ2x2ak5oSGYKTDEvV0xwdGw5UmhmOTBQK0UvdUlpSVYvUHc5bG52SHJ2MElwdDRLazVRV29uSUxzaWJCSEZUeG1US25zUHIxYQpBRCszNTZZdmpSdU5ZZUR5V0JjMm1LQUkwbk8rYnRicnpPQzl4d2JmUHdtUGlaMVZKUktNeGRqSmRuMHVoU3RSCnRPd09UczVJamtLQWRHMXhwU2ExeDFtS0F2c0ZnUURkQmJuL25FWGkvMkhGN1dPK2hBUDhkUEJ3ZmdRR2QycTQKU0VrZTJlODlNMzNscEVPOGQ3M2pHcFo1bWZMTFVzTFEKLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  usages:
    - digital signature
    - key encipherment
    - client auth
