apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentication-microservice
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: authentication-microservice

spec:
  project: default

  source:
    repoURL: https://github.com/Archisman-Mridha/instagram-clone
    targetRevision: staging
    path: kubernetes/base/microservices/authentication
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true