apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentication-microservice
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: authentication-microservice=archismanmridha/instagram-clone-authentication-microservice
    argocd-image-updater.argoproj.io/authentication-microservice.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-credentials
    argocd-image-updater.argoproj.io/git-branch: staging

spec:
  project: default

  source:
    repoURL: https://github.com/Archisman-Mridha/instagram-clone
    targetRevision: staging
    path: kubernetes/base/microservices/authentication

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true