apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-microservice
  namespace: default
  labels:
    app.kubernetes.io/part-of: authentication-microservice

spec:
  selector:
    matchLabels:
      app: authentication-microservice
  template:
    metadata:
      labels:
        app: authentication-microservice
    spec:

      containers:
        - name: authentication-microservice
          image: archismanmridha/instagram-clone-authentication-microservice:a2b071a81c1ceda6d2405115b901d0e9ed5a6aef
          resources:
            limits:
              memory: 128Mi
              cpu: 200m
          ports:
            - containerPort: 4000
          envFrom:
            - secretRef:
                name: authentication-microservice-envs