apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: sealed-secrets
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: sealed-secrets
    app.kubernetes.io/part-of: sealed-secrets
    app.kubernetes.io/version: 0.37.0
    app.tanka.grafana.com: sealed-secrets
    helm.sh/chart: sealed-secrets-2.18.6
  name: sealed-secrets-controller
  namespace: sealed-secrets
spec:
  ports:
    - name: http
      nodePort: null
      port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: sealed-secrets
    app.kubernetes.io/name: sealed-secrets
  type: ClusterIP
