apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 86.1.0
    app.tanka.grafana.com: kube-prometheus-stack
    chart: kube-prometheus-stack-86.1.0
    heritage: Helm
    release: kube-prometheus-stack
  name: kube-prometheus-stack-prometheus
  namespace: kube-prometheus-stack
spec:
  endpoints:
    - path: /metrics
      port: http-web
    - path: /metrics
      port: reloader-web
  namespaceSelector:
    matchNames:
      - kube-prometheus-stack
  selector:
    matchLabels:
      app: kube-prometheus-stack-prometheus
      release: kube-prometheus-stack
      self-monitor: "true"
