apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 13.0.1-security-01
    app.tanka.grafana.com: kube-prometheus-stack
    helm.sh/chart: grafana-12.4.1
    release: kube-prometheus-stack
  name: kube-prometheus-stack-grafana
  namespace: kube-prometheus-stack
spec:
  endpoints:
    - honorLabels: true
      path: /metrics
      port: http-web
      scheme: http
  jobLabel: kube-prometheus-stack
  namespaceSelector:
    matchNames:
      - kube-prometheus-stack
  selector:
    matchLabels:
      app.kubernetes.io/instance: kube-prometheus-stack
      app.kubernetes.io/name: grafana
