apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: aws-node-termination-handler
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: aws-node-termination-handler
    app.kubernetes.io/part-of: aws-node-termination-handler
    app.kubernetes.io/version: 1.25.6
    app.tanka.grafana.com: aws-node-termination-handler
    helm.sh/chart: aws-node-termination-handler-0.27.6
  name: aws-node-termination-handler
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - get
  - apiGroups:
      - ""
    resources:
      - pods/eviction
    verbs:
      - create
  - apiGroups:
      - extensions
    resources:
      - daemonsets
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - daemonsets
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
