apiVersion: instagramclone.io/v1alpha1
kind: Application
metadata:
  name: posts-microservice
  namespace: microservices

spec:
  image: ghcr.io/archisman-mridha/instagram-clone-posts-microservice:5516c30f64f06c5cd86589ddb19e23e1d5b18cc7
  replicas:
    min: 2
    max: 3
  resources:
    cpu: 100m
    memory: 100Mi
  secretName: posts-microservice
  port: 4000