apiVersion: instagramclone.io/v1alpha1
kind: Application
metadata:
  name: users-microservice
  namespace: microservices

spec:
  image: ghcr.io/archisman-mridha/instagram-clone-users-microservice:9574f877a5a231dbab94fa621fac97734ad5227e
  replicas:
    min: 2
    max: 3
  resources:
    cpu: 100m
    memory: 100Mi
  secretName: users-microservice
  port: 4000