resources:

  # Cloudnative PG operator.
  - https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/release-1.20/releases/cnpg-1.20.1.yaml

  # ArgoCD Image Updater
  - https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/stable/manifests/install.yaml
  - ./git-credentials.secret.yaml

  - ./microservices/microservices.argocd-application.yaml