apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: operator
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/part-of: kubescape
    app.kubernetes.io/version: 1.40.2
    app.tanka.grafana.com: kubescape
    helm.sh/chart: kubescape-operator-1.40.2
    kubescape.io/ignore: "true"
    kubescape.io/tier: core
    tier: ks-control-plane
  name: operator
  namespace: kubescape
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: operator
      app.kubernetes.io/instance: kubescape
      app.kubernetes.io/name: kubescape-operator
  strategy:
    rollingUpdate:
      maxSurge: 0%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/capabilities-config: 8ded90bb710fd23e75fffae38866ba830ec3248895f13791d8966c96de65837f
        checksum/cloud-config: 3879d226bb5751c63c50c606f70fa2e51e342c3bd5939bb1afaa548c67ee242f
        checksum/cloud-secret: 192498af36fa8b505f01b472407fcc09b948e1259f80663d34f3f3885cdf0d25
        checksum/matching-rules-config: 7732c83da6cd6962f78ef323206eba8810b7a4fa3f21d1608d9c083428a6eb8f
        checksum/operator-config: 979468439f64547aa81c6410b8da45179ce4cb6fb3e2df631aaa1476c6b75866
      labels:
        app: operator
        app.kubernetes.io/component: operator
        app.kubernetes.io/instance: kubescape
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: kubescape-operator
        app.kubernetes.io/part-of: kubescape
        app.kubernetes.io/version: 1.40.2
        helm.sh/chart: kubescape-operator-1.40.2
        kubescape.io/ignore: "true"
        kubescape.io/tier: core
        tier: ks-control-plane
    spec:
      affinity: null
      automountServiceAccountToken: true
      containers:
        - env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: HELM_RELEASE
              value: kubescape-operator-1.40.2
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  divisor: "1"
                  resource: limits.memory
            - name: KS_LOGGER_LEVEL
              value: info
            - name: KS_LOGGER_NAME
              value: zap
          image: quay.io/kubescape/operator:v0.2.142
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /v1/liveness
              port: readiness-port
            initialDelaySeconds: 3
            periodSeconds: 3
          name: operator
          ports:
            - containerPort: 4002
              name: trigger-port
              protocol: TCP
            - containerPort: 8000
              name: readiness-port
              protocol: TCP
            - containerPort: 8443
              name: admission-port
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /v1/readiness
              port: readiness-port
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            limits:
              cpu: 300m
              memory: 300Mi
            requests:
              cpu: 50m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          volumeMounts:
            - mountPath: /etc/credentials
              name: cloud-secret
              readOnly: true
            - mountPath: /tmp
              name: tmp-dir
            - mountPath: /etc/config/clusterData.json
              name: ks-cloud-config
              readOnly: true
              subPath: clusterData.json
            - mountPath: /etc/config/capabilities.json
              name: ks-capabilities
              readOnly: true
              subPath: capabilities.json
            - mountPath: /etc/config/matchingRules.json
              name: cs-matching-rules
              readOnly: true
              subPath: matchingRules.json
            - mountPath: /etc/config/config.json
              name: config
              readOnly: true
              subPath: config.json
            - mountPath: /etc/certs
              name: tls-certs
              readOnly: true
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        fsGroup: 65532
        runAsUser: 65532
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: operator
      tolerations: null
      volumes:
        - name: cloud-secret
          secret:
            secretName: cloud-secret
        - name: tls-certs
          secret:
            secretName: kubescape-admission-webhook-tls
        - emptyDir: {}
          name: tmp-dir
        - configMap:
            items:
              - key: clusterData
                path: clusterData.json
            name: ks-cloud-config
          name: ks-cloud-config
        - configMap:
            items:
              - key: capabilities
                path: capabilities.json
            name: ks-capabilities
          name: ks-capabilities
        - configMap:
            items:
              - key: config.json
                path: config.json
            name: operator
          name: config
        - configMap:
            items:
              - key: matchingRules.json
                path: matchingRules.json
            name: cs-matching-rules
          name: cs-matching-rules
