apiVersion: v1
kind: Pod
metadata:
  annotations:
    helm.sh/hook: test
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    app.kubernetes.io/component: test-request-reply
    app.kubernetes.io/instance: openobserve
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: nats
    app.kubernetes.io/version: 2.11.8
    app.tanka.grafana.com: openobserve
    helm.sh/chart: nats-1.3.13
  name: openobserve-nats-test-request-reply
  namespace: default
spec:
  containers:
    - args:
        - sh
        - -ec
        - nats reply --echo echo & pid="$!"; sleep 1; nats request echo hi > /tmp/resp; kill "$pid"; wait; grep -qF hi /tmp/resp
      command:
        - sh
        - -ec
        - |
          work_dir="$(pwd)"
          mkdir -p "$XDG_CONFIG_HOME/nats"
          cd "$XDG_CONFIG_HOME/nats"
          if ! [ -s context ]; then
            ln -s /etc/nats-contexts context
          fi
          if ! [ -f context.txt ]; then
            echo -n "default" > context.txt
          fi
          cd "$work_dir"
          exec /entrypoint.sh "$@"
        - --
      image: natsio/nats-box:0.18.0-nonroot
      name: nats-box
      volumeMounts:
        - mountPath: /etc/nats-contexts
          name: contexts
  enableServiceLinks: false
  restartPolicy: Never
  volumes:
    - name: contexts
      secret:
        secretName: openobserve-nats-box-contexts
