services:
  siglens:
    image: siglens/siglens:0.2.1
    container_name: siglens
    ports:
      - 8081:8081
      - 5122:5122

  vector:
    image: timberio/vector:0.37.1-alpine
    container_name: vector
    volumes:
      - ./configs/vector.yaml:/etc/vector/vector.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    command: [-c, /etc/vector/vector.yaml]
    ports:
      - 8686:8686
    depends_on:
      - siglens

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    hostname: jaeger
    ports:
      - 4317:4317
      - 16686:16686
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./configs/prometheus.yaml:/etc/prometheus/prometheus.yml:ro

  autometrics:
    container_name: autometrics
    image: autometrics/am-proxy
    environment:
      - PROMETHEUS_URL=http://prometheus:9090
    ports:
      - 6789:6789
