resources:
  - namespace.yaml
  - main-cluster-init-sql.sealed-secret.yaml
  - cluster.yaml
  - admin-credentials.sealed-secret.yaml
  - grafana-dashboard.configmap.yaml
  - atlasgo-credentials.sealed-secret.yaml
  - schema.yaml

helmCharts:
  - repo: https://cloudnative-pg.io/charts
    name: cloudnative-pg
    releaseName: cloudnative-pg
    namespace: cloudnative-pg
    version: 0.20.0
