[package]
name = "users-microservice"
version = "1.0.0"
edition = "2024"

[lib]
path = "wasm/lib.rs"
crate-type = ["cdylib"]

[dependencies]
validator = { workspace = true }
wit-bindgen = { workspace = true }
