apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-controller
  namespace: default

spec:
  replicas: 1
  selector:
    matchLabels:
      app: application-controller
  template:
    metadata:
      labels:
        app: application-controller
    spec:
      serviceAccountName: application-controller
      containers:
        - name: application-controller
          image: ghcr.io/archisman-mridha/instagram-clone-application-controller:0e132f1998e5208cc9c71ab60d2e70cc7d2940d3
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 200m
