apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-controller
  namespace: default

spec:
  replicas: 1
  selector:
    matchLabels:
      app: application-controller
  template:
    metadata:
      labels:
        app: application-controller
    spec:
      serviceAccountName: application-controller
      containers:
        - name: application-controller
          image: ghcr.io/archisman-mridha/instagram-clone-application-controller:5516c30f64f06c5cd86589ddb19e23e1d5b18cc7
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 200m
