apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: strimzi
    app.kubernetes.io/managed-by: Helmraiser
    app.tanka.grafana.com: strimzi
    chart: strimzi-kafka-operator-0.35.0
    component: entity-operator-role-binding
    heritage: Helm
    release: strimzi
  name: strimzi-cluster-operator-entity-operator-delegation
  namespace: strimzi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: strimzi-entity-operator
subjects:
  - kind: ServiceAccount
    name: strimzi-cluster-operator
    namespace: strimzi
