apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: nats
    app.kubernetes.io/instance: openobserve
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: nats
    app.kubernetes.io/version: 2.11.8
    app.tanka.grafana.com: openobserve
    helm.sh/chart: nats-1.3.13
  name: openobserve-nats-headless
  namespace: default
spec:
  clusterIP: None
  ports:
    - appProtocol: tcp
      name: nats
      port: 4222
      targetPort: nats
    - appProtocol: tcp
      name: cluster
      port: 6222
      targetPort: cluster
    - appProtocol: http
      name: monitor
      port: 8222
      targetPort: monitor
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/component: nats
    app.kubernetes.io/instance: openobserve
    app.kubernetes.io/name: nats
