scrape_configs:
  - job_name: gateway
    metrics_path: /metrics
    static_configs:
      - targets: ["gateway:4000"]
    # NOTE - For a real deployment, you would want the scrape interval to be longer but for testing,
    # you want the data to show up quickly
    scrape_interval: 200ms

  - job_name: users-microservice
    metrics_path: /metrics
    static_configs:
      - targets: ["users-microservice:5000"]
    scrape_interval: 200ms

  - job_name: profiles-microservice
    metrics_path: /metrics
    static_configs:
      - targets: ["profiles-microservice:5000"]
    scrape_interval: 200ms

  - job_name: followships-microservice
    metrics_path: /metrics
    static_configs:
      - targets: ["followships-microservice:5000"]
    scrape_interval: 200ms

  - job_name: posts-microservice
    metrics_path: /metrics
    static_configs:
      - targets: ["posts-microservice:5000"]
    scrape_interval: 200ms

  - job_name: feeds-microservice
    metrics_path: /metrics
    static_configs:
      - targets: ["feeds-microservice:5000"]
    scrape_interval: 200ms
