directory: charts
repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: argo
    url: https://argoproj.github.io/argo-helm
requires:
  - chart: argo/argo-cd
    version: 7.6.5
version: 1
