apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/managed-by: Helmraiser
    app.tanka.grafana.com: kubescape
  name: securityexceptions.kubescape.io
spec:
  group: kubescape.io
  names:
    kind: SecurityException
    plural: securityexceptions
    shortNames:
      - se
    singular: securityexception
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - jsonPath: .spec.reason
          name: Reason
          type: string
        - jsonPath: .spec.expiresAt
          name: Expires
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      name: v1beta1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                author:
                  type: string
                expiresAt:
                  format: date-time
                  type: string
                match:
                  properties:
                    images:
                      items:
                        type: string
                      type: array
                    objectSelector:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    resources:
                      items:
                        properties:
                          apiGroup:
                            type: string
                          kind:
                            type: string
                          name:
                            type: string
                        required:
                          - kind
                        type: object
                      type: array
                  type: object
                posture:
                  items:
                    properties:
                      action:
                        enum:
                          - ignore
                          - alert_only
                        type: string
                      controlID:
                        type: string
                      frameworkName:
                        type: string
                    required:
                      - controlID
                      - action
                    type: object
                  type: array
                reason:
                  type: string
                vulnerabilities:
                  items:
                    properties:
                      expiredOnFix:
                        type: boolean
                      impactStatement:
                        type: string
                      justification:
                        enum:
                          - component_not_present
                          - vulnerable_code_not_present
                          - vulnerable_code_not_in_execute_path
                          - vulnerable_code_cannot_be_controlled_by_adversary
                          - inline_mitigations_already_exist
                        type: string
                      status:
                        enum:
                          - not_affected
                          - fixed
                          - under_investigation
                        type: string
                      vulnerability:
                        properties:
                          aliases:
                            items:
                              type: string
                            type: array
                          id:
                            type: string
                        required:
                          - id
                        type: object
                    required:
                      - vulnerability
                      - status
                    type: object
                  type: array
              type: object
            status:
              type: object
          required:
            - spec
          type: object
      served: true
      storage: true
      subresources:
        status: {}
