apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: jaeger
  namespace: argocd

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: jaeger

  source:
    repoURL: https://jaegertracing.github.io/helm-charts
    chart: jaeger
    targetRevision: 0.72.0
    helm:
      releaseName: jaeger
      valuesObject:

        ## Jaeger provisions a Cassandra datastore to store distributed traces.
        cassandra:
          persistence:
            enabled: true
            size: 1Gi
          config:
            cluster_size: 1

        agent:
          enabled: false

        collector:
          service:
            otlp:
              grpc:
                name: otlp-grpc
                port: 4317
              http:
                name: otlp-http
                port: 4318

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true