apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dragonfly-operator
    app.kubernetes.io/instance: dragonfly
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: dragonfly-operator
    app.kubernetes.io/part-of: dragonfly-operator
    app.kubernetes.io/version: v1.5.0
    app.tanka.grafana.com: dragonfly
    helm.sh/chart: dragonfly-operator-v1.5.0
  name: dragonfly-dragonfly-operator-manager-role
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - dragonflydb.io
    resources:
      - dragonflies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - dragonflydb.io
    resources:
      - dragonflies/finalizers
    verbs:
      - update
  - apiGroups:
      - dragonflydb.io
    resources:
      - dragonflies/status
    verbs:
      - get
      - patch
      - update
