---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-dns-api-key
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_key: AgDxisDpghvEbg61kZK8fTt8dHAP/4BK6xnbqi+Udg1B7X4GYp8wdTsWFv4LLrj2ZFL3VaKOnWQYto2CsfbW1iKrhHfC9Yw0rljIJXj7ya8A8oFmOMwRi4af/ocNMeRxav3FbrR5YtaQLabE9vIM9Lrq9f9B68/x4ZuowDMqYpVTkaIGf+ufu+N9Z8qlhBXkAv8v3vw2FONXD2PVivoBptbZqtRTVt+p+B3hVk/WBfs9Sds9HH6OMgGBM1kInrGoNGkUmTJ5eytBfvyQG/B/rABux2IjJXoCOXTgcmQVb196y/Kl1o2TxlGzY6mrdkfRRNGFM+zYIX+u0Du3rTX6BfbcK1jXUW6RHmxEDBZiN2aZQE87z0MCzs+tLLEsanJFK1q2/kPn4cI4khsp5ZsCdd2XgKFhX0HDJfFqxRK2ef+vIheZLhRd8OF9NkCXy9eGXfxPtVYmEjF4E6zKVRiMHEmq98Bu3qWY7fWB9QrsT4+XUABfdruJLWaAkHo8kH4MxIagFD0bwq57Ni/tmpkohgwkYZGS6tOQ4t7Woc0ejwVHZtSkQ2HOLkYR/mQhrvNh/SnF+1hWkTVs8Cf0r4LFixY5ZpVBU9S6KeGNd7UNab3T39Y1EpEq8EzOOomTe3cJLV0RReImygINEsXuGJTX082bWz0EtD6xZoTYY4U71ZR+zVpGTjMoogIK6zp1eHOGYdfP3cWcCFjWOIPdilhKyfB73yb6CKJ7pbckYrNHGK1Ut9ml44SR
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-dns-api-key
      namespace: external-dns
