apiVersion: instagramclone.io/v1alpha1
kind: Application
metadata:
  name: posts-microservice
  namespace: microservices
  labels:
    app: posts-microservice
    app.kubernetes.io/instance: posts-microservice

spec:
  image: ghcr.io/archisman-mridha/instagram-clone-posts-microservice:89d47a5a4cffbab586f2609fbc8d4e3f07152f3c
  replicas:
    min: 1
    max: 3
  resources:
    cpu: 100m
    memory: 100Mi
  secretName: posts-microservice
  ports:
    - name: grpc
      containerPort: 4000
    - name: metrics
      containerPort: 5000
