apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app.tanka.grafana.com: openobserve
  name: openobserve
  namespace: openobserve
spec:
  podMetricsEndpoints:
    - port: metrics
  selector:
    matchLabels:
      cnpg.io/cluster: openobserve
