apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  labels:
    app.tanka.grafana.com: openmedia
    strimzi.io/cluster: openmedia
  name: openmedia-openmedia-backend
  namespace: openmedia
spec:
  authorization:
    acls:
      - host: "*"
        operations:
          - Describe
          - Read
          - Write
        resource:
          name: events.users.created
          patternType: literal
          type: topic
      - host: "*"
        operations:
          - Describe
          - Read
          - Write
        resource:
          name: events.profiles.created
          patternType: literal
          type: topic
      - host: "*"
        operations:
          - Read
        resource:
          name: openmedia-backend
          patternType: prefix
          type: group
    type: simple
