apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: dragonfly-operator
    app.kubernetes.io/instance: dragonfly
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: dragonfly-operator
    app.kubernetes.io/part-of: dragonfly-operator
    app.kubernetes.io/version: v1.5.0
    app.tanka.grafana.com: dragonfly
    helm.sh/chart: dragonfly-operator-v1.5.0
  name: dragonfly-dragonfly-operator-controller-svc
  namespace: dragonfly
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: metrics
  selector:
    app.kubernetes.io/instance: dragonfly
    app.kubernetes.io/name: dragonfly-operator
    control-plane: controller-manager
  type: ClusterIP
