apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: Helmraiser
    app.tanka.grafana.com: openkruise
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: aggregate-kruise-edit
rules:
  - apiGroups:
      - apps.kruise.io
    resources:
      - advancedcronjobs
      - broadcastjobs
      - clonesets
      - clonesets/scale
      - containerrecreaterequests
      - daemonsets
      - imagelistpulljobs
      - imagepulljobs
      - nodeimages
      - nodepodprobes
      - persistentpodstates
      - podprobemarkers
      - sidecarsets
      - statefulsets
      - statefulsets/scale
      - uniteddeployments
      - uniteddeployments/scale
      - workloadspreads
    verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
