# Extensions are a powerful feature of the Grafbase Gateway that lets you extend its functionality
# with custom code.
# You can write extensions in Rust and compile them into a WebAssembly module that the Grafbase
# Gateway loads. Extensions implement custom authentication, authorization, and resolving logic,
# and integrate with external services and APIs.
[extensions]
grpc = "0.1.2"

[subgraphs.users]
schema_path = "../generated/subgraphs/users/schema.graphql"

[[extensions.grpc.config.services]]
name = "microservices.users.UsersService"
address = "localhost:4001"

[subgraphs.profiles]
schema_path = "../generated/subgraphs/profiles/schema.graphql"

[[extensions.grpc.config.services]]
name = "microservices.profiles.ProfilesService"
address = "localhost:4002"

[subgraphs.followships]
schema_path = "../generated/subgraphs/followships/schema.graphql"

[[extensions.grpc.config.services]]
name = "microservices.followships.FollowshipsService"
address = "localhost:4003"

[subgraphs.posts]
schema_path = "../generated/subgraphs/posts/schema.graphql"

[[extensions.grpc.config.services]]
name = "microservices.posts.PostsService"
address = "localhost:4004"

[subgraphs.feeds]
schema_path = "../generated/subgraphs/feeds/schema.graphql"

[[extensions.grpc.config.services]]
name = "microservices.feeds.FeedsService"
address = "localhost:4005"
