## What is Bitnami Sealed Secrets - https://www.youtube.com/watch?v=xd2QoV6GJlc.

apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: bitnami-sealed-secrets
  namespace: argocd

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: 2.13.1
    helm:
      releaseName: sealed-secrets
      valuesObject:

        ## The Helm chart by default installs the controller with the name sealed-secrets, while the
        ## kubeseal command line interface (CLI) tries to access the controller with the name
        ## sealed-secrets-controller. So we enforce the controller name to be sealed-secrets-controller.
        fullnameOverride: sealed-secrets-controller
        ## Note also that kubeseal assumes that the controller is installed within the kube-system
        ## namespace by default.

        ## The name of an existing TLS secret containing the key used to encrypt secrets.
        secretName: "sealed-secrets-key"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true