apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: dragonfly
  namespace: argocd

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: dragonfly

  source:
    repoURL: https://github.com/Archisman-Mridha/instagram-clone
    targetRevision: HEAD
    path: kubernetes/manifests/dragonfly

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
