apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: istio
  namespace: argocd

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system

  source:
    repoURL: https://github.com/Archisman-Mridha/instagram-clone
    targetRevision: HEAD
    path: kubernetes/manifests/istio
    plugin:
      name: kustomize-enable-helm

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
