resources:
  - application-controller.application.yaml
  - bitnami-sealed-secrets.application.yaml
  - cloudnative-pg.application.yaml
  - cert-manager.application.yaml
  - debezium.application.yaml
  - dragonfly.application.yaml
  - elasticsearch.application.yaml
  - external-dns.application.yaml
  # - falco.application.yaml
  # - istio.application.yaml
  - jaeger.application.yaml
  - kube-prometheus-stack.application.yaml
  - kubescape.application.yaml
  - microservices.application.yaml
  - opa-gatekeeper.application.yaml
  - strimzi.application.yaml
