apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: metrics-server
  namespace: argocd

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  source:
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    chart: metrics-server
    targetRevision: 3.11.0
    helm:
      releaseName: metrics-server
      valuesObject: { }

  syncPolicy:
    automated:
      prune: true
      selfHeal: true