apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: storage
    app.kubernetes.io/component: storage
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/part-of: kubescape
    app.kubernetes.io/version: 1.40.2
    app.tanka.grafana.com: kubescape
    helm.sh/chart: kubescape-operator-1.40.2
    kubescape.io/ignore: "true"
    tier: ks-control-plane
  name: storage
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - services
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - flowcontrol.apiserver.k8s.io
    resources:
      - prioritylevelconfigurations
      - flowschemas
    verbs:
      - get
      - watch
      - list
