apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: database-engineer
  namespace: databases

rules:
  ## Permission to do anything in the databases namespace.
  - apiGroups:
      - ""
    resources:
      - "*"
    verbs:
      - "*"
