apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: physical-user

rules:
  ## Allow a physical user to create his/her own CertificateSigningRequest.
  - apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests
    verbs:
      - create
