devMode: True
debugLogging: True

serverPort: 4001

kafka:
  seedBrokerURLs: localhost:29092

postgres:
  url: postgres://default:XHwjzpbA3d32UGYT@localhost:5432/instagram_clone?sslmode=disable

elasticsearch:
  nodeAddresses: http://localhost:9200
  username: default
  password: XHwjzpbA3d32UGYT

openTelemetryCollectorURL: localhost:4317

flagsmith:
  url: https://edge.api.flagsmith.com/api/v1/identities/?identifier=default
  apiKey: S44DpTum6rRUsDp4GTiEwh
  clientName: users-microservice
