apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: csi-driver
    app.kubernetes.io/instance: aws-ebs-csi-driver
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: aws-ebs-csi-driver
    app.kubernetes.io/version: 1.60.1
    app.tanka.grafana.com: aws-ebs-csi-driver
    helm.sh/chart: aws-ebs-csi-driver-2.60.1
  name: ebs-csi-node-role
rules:
  - apiGroups:
      - storage.k8s.io
    resources:
      - volumeattachments
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - patch
      - list
      - watch
  - apiGroups:
      - storage.k8s.io
    resources:
      - csinodes
    verbs:
      - get
