apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: csi-driver
    app.kubernetes.io/instance: aws-ebs-csi-driver
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: aws-ebs-csi-driver
    app.kubernetes.io/version: 1.60.1
    app.tanka.grafana.com: aws-ebs-csi-driver
    helm.sh/chart: aws-ebs-csi-driver-2.60.1
  name: ebs-external-snapshotter-role
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - snapshot.storage.k8s.io
    resources:
      - volumesnapshotclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - snapshot.storage.k8s.io
    resources:
      - volumesnapshotcontents
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - snapshot.storage.k8s.io
    resources:
      - volumesnapshotcontents/status
    verbs:
      - update
      - patch
  - apiGroups:
      - groupsnapshot.storage.k8s.io
    resources:
      - volumegroupsnapshotclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - groupsnapshot.storage.k8s.io
    resources:
      - volumegroupsnapshotcontents
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - groupsnapshot.storage.k8s.io
    resources:
      - volumegroupsnapshotcontents/status
    verbs:
      - update
      - patch
