apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: argocd-redis
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v3.4.3
    app.tanka.grafana.com: argo-cd
    helm.sh/chart: argo-cd-9.5.19
  name: argo-cd-argocd-redis
  namespace: argo-cd
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: redis
  selector:
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/name: argocd-redis
