apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: applicationset-controller
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: argocd-applicationset-controller
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v3.4.3
    app.tanka.grafana.com: argo-cd
    helm.sh/chart: argo-cd-9.5.19
  name: argo-cd-argocd-applicationset-controller
  namespace: argo-cd
spec:
  ports:
    - name: http-webhook
      port: 7000
      targetPort: webhook
  selector:
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/name: argocd-applicationset-controller
  type: ClusterIP
