---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: default-credentials
  namespace: dragonfly
spec:
  encryptedData:
    password: AgAgBxHtV4tGb7YQDVr2XxNXPUeUU0P76jo3DPtrtaSX/O/LxqAjrogH31ZtLFtkx3hqNiU9fdZCooAjq43h3CAqj/bSOuigjmikm2JR3lGOQiOFMGzpa9zmJ6P7S54Kux5dhCTGJfgZWGI63Ol53uoQeymMjImjOXLqJQY2EHKwhaNyX+RWy/wev17cukWW2aBZWiywPxtSSqLPJmPEeEgwNjnkigAHa58h5AtCREMD8PffCP/f9RZ696/L+XSq/7TfmEWQGIS0tlg5EPnRC+2MgJswkzVBE6d4GXKOeVcE1ot4bbruXDp3JNVX6J4RTAI8wLQT6TC1n/hPfyYRoLJKLr2GM3ypmjr2UdKUJ7PoUymX4HQeV78Uz976b98/Z7pdo9Z935w96UWrBMclbG3bpZ/PlNmpMooVYjgExx3efHJLH0qXfA7Lu+eKJqQSMi8OuunmNVGB7mUdAYcFXucHgvcsZAUGqMtT1nKQ0exHOwsf47/2VbsgAtT9fX0/whrQfvZUTfmpUd42ybrzmm+KnActgz32zMXs57yL2MwdghEAc4HpXISHzGeyOX0EF5EZAMwz56UjIVsUQBszU0eVdg408gN6lbMqxz3gHRlx4ztgjlDCLxmct6wHra6+BmsdkVU4HWuPgl9745t2EQAnuEyxRThfJ3BRCzA4IVgsX4RW2xFIcl7mVlqZeWYEl401eDj1lxt21nbIbuJeOCk=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: default-credentials
      namespace: dragonfly
    type: Opaque
