apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  labels:
    app: storage
    app.kubernetes.io/component: storage
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/part-of: kubescape
    app.kubernetes.io/version: 1.40.2
    app.tanka.grafana.com: kubescape
    helm.sh/chart: kubescape-operator-1.40.2
    kubescape.io/ignore: "true"
    tier: ks-control-plane
  name: v1beta1.spdx.softwarecomposition.kubescape.io
spec:
  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURGVENDQWYyZ0F3SUJBZ0lRUjhWVU4zWWdtYStPTDFXUjFkZ2xmREFOQmdrcWhraUc5dzBCQVFzRkFEQVYKTVJNd0VRWURWUVFERXdwemRHOXlZV2RsTFdOaE1CNFhEVEkyTURjek1ESXpNekl5TWxvWERUSTRNRGN5T1RJegpNekl5TWxvd0ZURVRNQkVHQTFVRUF4TUtjM1J2Y21GblpTMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFECmdnRVBBRENDQVFvQ2dnRUJBTVFyWUF6bDdoL3ZDUEUya1ZvdHhhWmtlRGdCRUI1bm84WVBlWWNZdEcwRktNazcKMW0rTFZKTzFDUmhMQ2Z0eS95VXNBNlBHdXZNWGlBZUtIcW16VzRleDNUSzduS1daK3ZGM1RiQzR4YTh3RDE2NApUMDBVVlVyU0hObk5hRkJyK2toZ2luR21zcEZIQ2N0djlHdWpwUmViNk5RVGdvcXNLZGJnaVJvQUR4M2FrN0phCjkxZVdCVmRWNXdOMTBVYitXeTJ4RmNXd0hBOEV6a1ZvL05Gb055ZzV6RXcxME5Va3plMjVneEp3bk9oUzhrQ1kKdlBuYVpPbWEzeExrWVZreG5Zai9kbXBNSHpjM203TFZpS1V0T2ZxVGVvaStHc2RPK1pVSmd0V2V1d21ESVBCRApUSlNxVGhiN3ltOWxkMHppV3A4ZllZb2V2eURLV3AvNlRlbDExZjhDQXdFQUFhTmhNRjh3RGdZRFZSMFBBUUgvCkJBUURBZ0trTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVBCZ05WSFJNQkFmOEUKQlRBREFRSC9NQjBHQTFVZERnUVdCQlFpUnIwa2pxclBSZnlrZUJsUyt0bkkvU3RPcERBTkJna3Foa2lHOXcwQgpBUXNGQUFPQ0FRRUFhYU5DWTZvektKVmRxV1FieDdiK0JGbk1FcTViODA3UHBJSUpWdERKeFpyRmh6c1c4eEl5ClZzUFBoaytlZDRKbFdRc3lQMjdnR1oxMlZqQmp5N04wbDhSVldCTGdHcndMV0JJTzlsMmtXZ3dOcmlhd3pBT0gKbTkyaDRobjBST0hOWEdNQWwwMWZMKytTeVMwdTNOb3lOWEFjMDFPejQvQ2FmK1BjK0dBWEJkc0pacGVjb3N0NQpuQlNpWjVoRHVFQUFSa292ckppY09zYS9hdU1hendkWkVhNytENFZ4VnpIbnpVNWVrdVRpY2Mrd1BXNmZwR2pNCk1ja29lVU50KytkRENzdEJ5MmI1Um5XbGl6TEVVODYwZ2lqTW9IOXJwSTBNZ3VmeDR1MEx3V1BFM3pMU3NTemMKRk1SL01xdjZKcGNXV1FLa0NGOTA2ODlaRnVxV0RJOG5pZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  group: spdx.softwarecomposition.kubescape.io
  groupPriorityMinimum: 1000
  service:
    name: storage
    namespace: kubescape
  version: v1beta1
  versionPriority: 15
