apiVersion: v1
kind: Pod
metadata:
  annotations:
    helm.sh/hook: test
  labels:
    app.kubernetes.io/created-by: dragonfly-operator
    app.kubernetes.io/instance: dragonfly
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: dragonfly-operator
    app.kubernetes.io/part-of: dragonfly-operator
    app.kubernetes.io/version: v1.5.0
    app.tanka.grafana.com: dragonfly
    helm.sh/chart: dragonfly-operator-v1.5.0
  name: dragonfly-dragonfly-operator-test-connection
  namespace: dragonfly
spec:
  containers:
    - args:
        - dragonfly-dragonfly-operator:8443
      command:
        - wget
      image: busybox
      name: wget
  restartPolicy: Never
