apiVersion: v1
data:
  request-body.json: "{\"commands\":[{\"CommandName\":\"kubescapeScan\",\"args\":{\"scanV1\":{}}}]}"
kind: ConfigMap
metadata:
  labels:
    app: kubescape-scheduler
    app.kubernetes.io/component: kubescape-scheduler
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/part-of: kubescape
    app.kubernetes.io/version: 1.40.2
    app.tanka.grafana.com: kubescape
    helm.sh/chart: kubescape-operator-1.40.2
    kubescape.io/ignore: "true"
    kubescape.io/tier: core
    tier: ks-control-plane
  name: kubescape-scheduler
  namespace: kubescape
