apiVersion: instagramclone.io/v1alpha1
kind: Application
metadata:
  name: users-microservice
  namespace: microservices

spec:
  image: archismanmridha/instagram-clone-users-microservice:0.0.1-alpha
  replicas:
    min: 2
    max: 3
  resources:
    cpu: 100m
    memory: 100Mi
  secretName: users-microservice
  port: 4000
