# Sample Kubernetes Deployment, Service, Secret and HorizontalPodAutoscaler object definitions
# to deploy a microservice application to Kubernetes.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-microservice
  namespace: microservices
  labels:
    app.kubernetes.io/part-of: application-microservice
spec:
  selector:
    matchLabels:
      app: users-microservice
  template:
    metadata:
      labels:
        app: users-microservice
    spec:
      containers:
        - name: users-microservice
          image: ghcr.io/archisman-mridha/instagram-clone-users-microservice:f9dbce60bee1229eac7d12e66e2eb34bfb41d541
          resources:
            requests:
              memory: 128Mi
              cpu: 200m
            limits:
              memory: 256Mi
              cpu: 400m
          ports:
            - containerPort: 4000
          envFrom:
            - secretRef:
                name: users-microservice

---

apiVersion: v1
kind: Service
metadata:
  name: users-microservice
  namespace: microservices
  labels:
    app.kubernetes.io/part-of: application-microservice
spec:
  selector:
    app: users-microservice
  ports:
    - port: 4000
      targetPort: 4000

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: users-microservice
  namespace: microservices
  labels:
    app.kubernetes.io/part-of: application-microservice
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: users-microservice
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

---

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: users-microservice
  namespace: microservices
  labels:
    app.kubernetes.io/part-of: application-microservice
stringData:
  JWT_SECRET: secret
  GRPC_SERVER_PORT: 4000