apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/managed-by: Helmraiser
    app.tanka.grafana.com: kubearmor
    kubearmor-app: kubearmor-controller
  name: kubearmor-controller
  namespace: kubearmor
spec:
  replicas: 1
  selector:
    matchLabels:
      kubearmor-app: kubearmor-controller
  template:
    metadata:
      annotations:
        kubearmor-policy: audited
        kubectl.kubernetes.io/default-container: manager
      labels:
        kubearmor-app: kubearmor-controller
    spec:
      containers:
        - args:
            - --annotateExisting=false
          command:
            - /manager
          image: docker.io/kubearmor/kubearmor-controller:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          name: manager
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
            - mountPath: /sys/kernel/security
              name: sys-path
              readOnly: true
      securityContext:
        runAsNonRoot: true
      serviceAccountName: kubearmor-controller
      terminationGracePeriodSeconds: 10
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: kubearmor-controller-webhook-server-cert
        - hostPath:
            path: /sys/kernel/security
            type: Directory
          name: sys-path
