name: Build and push container images
on:
  push:
    branches:
      - main

jobs:
  build-containers:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: archismanmridha
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: backend/services/authentication/Dockerfile
          push: true
          tags: archismanmridha/instagram-clone-authentication-microservice:${{ github.sha }}