name: Build and push container images
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:

  check-code-changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
    outputs:
      backend: ${{ steps.filter.outputs.backend }}

  build-and-push-containers:
    needs: check-code-changes
    if: ${{ needs.changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container-image:
          - dockerfile: backend/services/authentication/Dockerfile
            tag: archismanmridha/instagram-clone-authentication-microservice
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: archismanmridha
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.container-image.dockerfile }}
          push: true
          tags: ${{ matrix.container-image.tag }}:${{ github.sha }}

          # experimental cache exporter for GitHub Actions provided by buildx and BuildKit.
          # It uses the GitHub Cache API to fetch and load the Docker layer cache blobs across
          # builds.
          cache-from: type=gha
          cache-to: type=gha,mode=max